### ISSUE TITLE
博主你好，我也在做多标签方面的检测，有些问题想问你，请问可以加你的Q吗，谢谢！

### ISSUE THREAD

**Issue by Tefor** [Code-keys/yolov5-6.0-RetinaNet-MultiLabel#4]
我的Q是126235060

**Comment by Code-keys** [comment]
2071476667

**Comment by Tefor** [comment]
> 2071476667

不好意思，你的Q验证问题，我通过不了。。。，请问能麻烦你加我嘛，1262350606

**Comment by Code-keys** [comment]
okey

**Comment by Tefor** [comment]
> okey

作者你好，我昨天申请你的好友了，但是你还没有通过，麻烦通过一下哈，或者我在这里问一下你的数据集大概用了多少张图片呢，还想咨询一下为什么train和val所使用的数据集类型不一样，能不能val也用multilabel格式的标签呢？
